// Generated by nitro

// App Config
import type { Defu } from 'defu';

import type { default as appConfig0 } from '../../app.config';
import type { default as appConfig1 } from '../../../../packages/ui/app.config';
import type { default as appConfig2 } from '../../../../packages/types/app.config';
import type { default as appConfig3 } from '../../../../packages/utils/app.config';
import type { default as appConfig4 } from '../../../../packages/tools/app.config';

type UserAppConfig = Defu<
  {},
  [
    typeof appConfig0,
    typeof appConfig1,
    typeof appConfig2,
    typeof appConfig3,
    typeof appConfig4
  ]
>;

declare module 'nitropack/types' {
  interface AppConfig extends UserAppConfig {}
}
export {};
