// ESLint config generated by Nuxt
/// <reference path="./eslint-typegen.d.ts" />
/* eslint-disable */
// @ts-nocheck

import typegen from '../../../node_modules/.pnpm/eslint-typegen@0.3.2_eslint@9.20.1/node_modules/eslint-typegen/dist/index.mjs';
import { createConfigForNuxt, defineFlatConfigs, resolveOptions } from '../../../node_modules/.pnpm/@nuxt+eslint-config@0.6.2_eslint@9.20.1_typescript@5.7.3/node_modules/@nuxt/eslint-config/dist/flat.mjs';
import { fileURLToPath } from 'url';

const r = (...args) => fileURLToPath(new URL(...args, import.meta.url))

export { defineFlatConfigs }

export const options = resolveOptions({
  features: {
  "standalone": true
},
  dirs: {
    pages: ["pages", "../../packages/ui/pages", "../../packages/types/pages", "../../packages/utils/pages", "../../packages/tools/pages"],
    composables: ["composables", "utils", "../../packages/ui/composables", "../../packages/ui/utils", "../../packages/types/composables", "../../packages/types/utils", "../../packages/utils/composables", "../../packages/utils/utils", "../../packages/tools/composables", "../../packages/tools/utils"],
    components: ["components", "../../packages/ui/components", "../../packages/types/components", "../../packages/utils/components", "../../packages/tools/components"],
    componentsPrefixed: [],
    layouts: ["layouts", "../../packages/ui/layouts", "../../packages/types/layouts", "../../packages/utils/layouts", "../../packages/tools/layouts"],
    plugins: ["plugins", "../../packages/ui/plugins", "../../packages/types/plugins", "../../packages/utils/plugins", "../../packages/tools/plugins"],
    middleware: ["middleware", "../../packages/ui/middleware", "../../packages/types/middleware", "../../packages/utils/middleware", "../../packages/tools/middleware"],
    modules: ["modules", "../../packages/ui/modules", "../../packages/types/modules", "../../packages/utils/modules", "../../packages/tools/modules"],
    servers: [],
    root: [r("..")],
    src: ["", "../../packages/ui", "../../packages/types", "../../packages/utils", "../../packages/tools"],
}
})

export const configs = createConfigForNuxt(options)

configs.append(
// Set globals from imports registry
{
  name: 'nuxt/import-globals',
  languageOptions: {
    globals: Object.fromEntries([].map(i => [i, 'readonly'])),
  },
}
)

export function withNuxt(...customs) {
  return configs
    .clone()
    .append(...customs)
    .onResolved(configs => typegen(configs, { dtsPath: r("./eslint-typegen.d.ts"), augmentFlatConfigUtils: true }))
}

export default withNuxt