// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "../../app.config";
import type { default as appConfig1 } from "../../../app.config";
import type { default as appConfig2 } from "../../../../types/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1, typeof appConfig2]>

declare module "nitropack/types" {
  interface AppConfig extends UserAppConfig {}

}
export {}