#!/bin/sh

# Start
echo "[husky]: Running pre-commit hook..."

# Check staged files
STAGED_FILES=$(git diff --cached --name-only)
echo "[husky]: Your staged files: $STAGED_FILES"

# Run lint-staged to lint only staged files
echo "[husky]: Running script: turbo run prelint"
pnpm turbo run prelint

# Run tests
echo "[husky]: Running script: turbo run pretest"
pnpm turbo run pretest

# Run Infisical scan on staged changes with baseline
echo "[husky]: Running command: pnpm infisical scan git-changes --staged --verbose --baseline-path .reports/secrets-report.json"
pnpm infisical scan git-changes --staged --verbose --baseline-path .reports/secrets-report.json

