// Generated by auto imports
export {}
declare global {
  const ClarityOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/clarity')['ClarityOptions']
  const CloudflareWebAnalyticsOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/cloudflare-web-analytics')['CloudflareWebAnalyticsOptions']
  const CrispOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/crisp')['CrispOptions']
  const FathomAnalyticsOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/fathom-analytics')['FathomAnalyticsOptions']
  const GoogleAdsenseOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-adsense')['GoogleAdsenseOptions']
  const GoogleAnalyticsOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-analytics')['GoogleAnalyticsOptions']
  const GoogleMapsOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-maps')['GoogleMapsOptions']
  const GoogleTagManagerOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-tag-manager')['GoogleTagManagerOptions']
  const HotjarOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/hotjar')['HotjarOptions']
  const IntercomOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/intercom')['IntercomOptions']
  const MatomoAnalyticsOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/matomo-analytics')['MatomoAnalyticsOptions']
  const MetaPixelOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/meta-pixel')['MetaPixelOptions']
  const NpmOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/npm')['NpmOptions']
  const PlausibleAnalyticsOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/plausible-analytics')['PlausibleAnalyticsOptions']
  const SegmentOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/segment')['SegmentOptions']
  const StripeOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/stripe')['StripeOptions']
  const XPixelOptions: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/x-pixel')['XPixelOptions']
  const abortNavigation: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['abortNavigation']
  const addRouteMiddleware: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['addRouteMiddleware']
  const avatarGroupInjectionKey: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup')['avatarGroupInjectionKey']
  const buttonGroupInjectionKey: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useButtonGroup')['buttonGroupInjectionKey']
  const callOnce: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/once')['callOnce']
  const cancelIdleCallback: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/compat/idle-callback')['cancelIdleCallback']
  const clearError: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/error')['clearError']
  const clearNuxtData: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/asyncData')['clearNuxtData']
  const clearNuxtState: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/state')['clearNuxtState']
  const computed: typeof import('vue')['computed']
  const createError: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/error')['createError']
  const customRef: typeof import('vue')['customRef']
  const defineAppConfig: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/nuxt')['defineAppConfig']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineLocale: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale')['defineLocale']
  const defineNuxtComponent: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/component')['defineNuxtComponent']
  const defineNuxtLink: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/components/nuxt-link')['defineNuxtLink']
  const defineNuxtPlugin: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/nuxt')['defineNuxtPlugin']
  const defineNuxtRouteMiddleware: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['defineNuxtRouteMiddleware']
  const definePayloadPlugin: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/nuxt')['definePayloadPlugin']
  const definePayloadReducer: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/payload')['definePayloadReducer']
  const definePayloadReviver: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/payload')['definePayloadReviver']
  const defineShortcuts: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts')['defineShortcuts']
  const effect: typeof import('vue')['effect']
  const effectScope: typeof import('vue')['effectScope']
  const extendDevtoolsMeta: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/extendDevtoolsMeta')['extendDevtoolsMeta']
  const extractShortcuts: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts')['extractShortcuts']
  const formBusInjectionKey: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['formBusInjectionKey']
  const formFieldInjectionKey: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['formFieldInjectionKey']
  const formInputsInjectionKey: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['formInputsInjectionKey']
  const formLoadingInjectionKey: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['formLoadingInjectionKey']
  const formOptionsInjectionKey: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['formOptionsInjectionKey']
  const getAppManifest: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/manifest')['getAppManifest']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const getRouteRules: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/manifest')['getRouteRules']
  const h: typeof import('vue')['h']
  const hasInjectionContext: typeof import('vue')['hasInjectionContext']
  const inject: typeof import('vue')['inject']
  const injectHead: typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['injectHead']
  const inputIdInjectionKey: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['inputIdInjectionKey']
  const isNuxtError: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/error')['isNuxtError']
  const isPrerendered: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/payload')['isPrerendered']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const isShallow: typeof import('vue')['isShallow']
  const isVue2: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/compat/vue-demi')['isVue2']
  const isVue3: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/compat/vue-demi')['isVue3']
  const kbdKeysMap: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useKbd')['kbdKeysMap']
  const loadPayload: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/payload')['loadPayload']
  const localeContextInjectionKey: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useLocale')['localeContextInjectionKey']
  const markRaw: typeof import('vue')['markRaw']
  const mergeModels: typeof import('vue')['mergeModels']
  const modalInjectionKey: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useModal')['modalInjectionKey']
  const navigateTo: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['navigateTo']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onNuxtReady: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ready')['onNuxtReady']
  const onPrehydrate: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['onPrehydrate']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const prefetchComponents: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/preload')['prefetchComponents']
  const preloadComponents: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/preload')['preloadComponents']
  const preloadPayload: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/payload')['preloadPayload']
  const preloadRouteComponents: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/preload')['preloadRouteComponents']
  const prerenderRoutes: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['prerenderRoutes']
  const provide: typeof import('vue')['provide']
  const proxyRefs: typeof import('vue')['proxyRefs']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const refreshCookie: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/cookie')['refreshCookie']
  const refreshNuxtData: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/asyncData')['refreshNuxtData']
  const reloadNuxtApp: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/chunk')['reloadNuxtApp']
  const requestIdleCallback: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/compat/idle-callback')['requestIdleCallback']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const setPageLayout: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['setPageLayout']
  const setResponseStatus: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['setResponseStatus']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const showError: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/error')['showError']
  const slideoverInjectionKey: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useSlideover')['slideoverInjectionKey']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const tryUseNuxtApp: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/nuxt')['tryUseNuxtApp']
  const unref: typeof import('vue')['unref']
  const updateAppConfig: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/config')['updateAppConfig']
  const useAppConfig: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/config')['useAppConfig']
  const useAsyncData: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/asyncData')['useAsyncData']
  const useAttrs: typeof import('vue')['useAttrs']
  const useAvatarGroup: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup')['useAvatarGroup']
  const useButtonGroup: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useButtonGroup')['useButtonGroup']
  const useColorMode: typeof import('../../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/composables')['useColorMode']
  const useComponentIcons: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons')['useComponentIcons']
  const useCookie: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/cookie')['useCookie']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useError: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/error')['useError']
  const useFetch: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/fetch')['useFetch']
  const useFormField: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['useFormField']
  const useHead: typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['useHead']
  const useHeadSafe: typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['useHeadSafe']
  const useHydration: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/hydrate')['useHydration']
  const useId: typeof import('vue')['useId']
  const useImage: typeof import('../../../../node_modules/.pnpm/@nuxt+image@1.9.0/node_modules/@nuxt/image/dist/runtime/composables')['useImage']
  const useKbd: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useKbd')['useKbd']
  const useLazyAsyncData: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/asyncData')['useLazyAsyncData']
  const useLazyFetch: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/fetch')['useLazyFetch']
  const useLoadingIndicator: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/loading-indicator')['useLoadingIndicator']
  const useLocale: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useLocale')['useLocale']
  const useModal: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useModal')['useModal']
  const useModel: typeof import('vue')['useModel']
  const useNuxtApp: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/nuxt')['useNuxtApp']
  const useNuxtData: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/asyncData')['useNuxtData']
  const usePreviewMode: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/preview')['usePreviewMode']
  const useRequestEvent: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['useRequestEvent']
  const useRequestFetch: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['useRequestFetch']
  const useRequestHeader: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['useRequestHeader']
  const useRequestHeaders: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['useRequestHeaders']
  const useRequestURL: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/url')['useRequestURL']
  const useResponseHeader: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['useResponseHeader']
  const useRoute: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['useRoute']
  const useRouteAnnouncer: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/route-announcer')['useRouteAnnouncer']
  const useRouter: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['useRouter']
  const useRuntimeConfig: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/nuxt')['useRuntimeConfig']
  const useRuntimeHook: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/runtime-hook')['useRuntimeHook']
  const useScript: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/composables/useScript')['useScript']
  const useScriptClarity: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/clarity')['useScriptClarity']
  const useScriptCloudflareWebAnalytics: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/cloudflare-web-analytics')['useScriptCloudflareWebAnalytics']
  const useScriptCrisp: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/crisp')['useScriptCrisp']
  const useScriptEventPage: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/composables/useScriptEventPage')['useScriptEventPage']
  const useScriptFathomAnalytics: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/fathom-analytics')['useScriptFathomAnalytics']
  const useScriptGoogleAdsense: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-adsense')['useScriptGoogleAdsense']
  const useScriptGoogleAnalytics: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-analytics')['useScriptGoogleAnalytics']
  const useScriptGoogleMaps: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-maps')['useScriptGoogleMaps']
  const useScriptGoogleTagManager: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-tag-manager')['useScriptGoogleTagManager']
  const useScriptHotjar: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/hotjar')['useScriptHotjar']
  const useScriptIntercom: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/intercom')['useScriptIntercom']
  const useScriptLemonSqueezy: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/lemon-squeezy')['useScriptLemonSqueezy']
  const useScriptMatomoAnalytics: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/matomo-analytics')['useScriptMatomoAnalytics']
  const useScriptMetaPixel: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/meta-pixel')['useScriptMetaPixel']
  const useScriptNpm: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/npm')['useScriptNpm']
  const useScriptPlausibleAnalytics: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/plausible-analytics')['useScriptPlausibleAnalytics']
  const useScriptSegment: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/segment')['useScriptSegment']
  const useScriptStripe: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/stripe')['useScriptStripe']
  const useScriptTriggerConsent: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/composables/useScriptTriggerConsent')['useScriptTriggerConsent']
  const useScriptTriggerElement: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/composables/useScriptTriggerElement')['useScriptTriggerElement']
  const useScriptVimeoPlayer: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/vimeo-player')['useScriptVimeoPlayer']
  const useScriptXPixel: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/x-pixel')['useScriptXPixel']
  const useScriptYouTubePlayer: typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/youtube-player')['useScriptYouTubePlayer']
  const useSeoMeta: typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['useSeoMeta']
  const useServerHead: typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['useServerHead']
  const useServerHeadSafe: typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['useServerHeadSafe']
  const useServerSeoMeta: typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['useServerSeoMeta']
  const useShadowRoot: typeof import('vue')['useShadowRoot']
  const useSlideover: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useSlideover')['useSlideover']
  const useSlots: typeof import('vue')['useSlots']
  const useState: typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/state')['useState']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useToast: typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useToast')['useToast']
  const useTransitionState: typeof import('vue')['useTransitionState']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
  const withCtx: typeof import('vue')['withCtx']
  const withDirectives: typeof import('vue')['withDirectives']
  const withKeys: typeof import('vue')['withKeys']
  const withMemo: typeof import('vue')['withMemo']
  const withModifiers: typeof import('vue')['withModifiers']
  const withScopeId: typeof import('vue')['withScopeId']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ShortcutConfig, ShortcutsConfig, ShortcutsOptions } from '../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.d'
  import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.d')
  // @ts-ignore
  export type { DevtoolsMeta } from '../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/extendDevtoolsMeta.d'
  import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/extendDevtoolsMeta.d')
  // @ts-ignore
  export type { UseComponentIconsProps } from '../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.d'
  import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.d')
  // @ts-ignore
  export type { KbdKey, KbdKeySpecific } from '../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.d'
  import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.d')
  // @ts-ignore
  export type { ModalState } from '../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useModal.d'
  import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useModal.d')
  // @ts-ignore
  export type { SlideoverState } from '../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useSlideover.d'
  import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useSlideover.d')
  // @ts-ignore
  export type { Toast } from '../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useToast.d'
  import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useToast.d')
  // @ts-ignore
  export type { ElementScriptTriggerOptions } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/composables/useScriptTriggerElement.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/composables/useScriptTriggerElement.d')
  // @ts-ignore
  export type { ClarityApi, ClarityInput } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/clarity.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/clarity.d')
  // @ts-ignore
  export type { CloudflareWebAnalyticsApi, CloudflareWebAnalyticsInput } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/cloudflare-web-analytics.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/cloudflare-web-analytics.d')
  // @ts-ignore
  export type { CrispInput, CrispApi } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/crisp.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/crisp.d')
  // @ts-ignore
  export type { FathomAnalyticsInput, FathomAnalyticsApi } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/fathom-analytics.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/fathom-analytics.d')
  // @ts-ignore
  export type { GoogleAdsenseInput, GoogleAdsenseApi } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-adsense.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-adsense.d')
  // @ts-ignore
  export type { GoogleAnalyticsInput } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-analytics.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-analytics.d')
  // @ts-ignore
  export type { GoogleMapsInput, GoogleMapsApi } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-maps.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-maps.d')
  // @ts-ignore
  export type { GoogleTagManagerInput } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-tag-manager.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-tag-manager.d')
  // @ts-ignore
  export type { HotjarApi, HotjarInput } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/hotjar.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/hotjar.d')
  // @ts-ignore
  export type { IntercomInput, IntercomApi } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/intercom.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/intercom.d')
  // @ts-ignore
  export type { LemonSqueezyInput, LemonSqueezyEventPayload, LemonSqueezyApi } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/lemon-squeezy.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/lemon-squeezy.d')
  // @ts-ignore
  export type { MatomoAnalyticsInput } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/matomo-analytics.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/matomo-analytics.d')
  // @ts-ignore
  export type { MetaPixelApi, MetaPixelInput } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/meta-pixel.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/meta-pixel.d')
  // @ts-ignore
  export type { NpmInput } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/npm.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/npm.d')
  // @ts-ignore
  export type { PlausibleAnalyticsInput, PlausibleAnalyticsApi } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/plausible-analytics.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/plausible-analytics.d')
  // @ts-ignore
  export type { SegmentInput, SegmentApi } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/segment.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/segment.d')
  // @ts-ignore
  export type { StripeInput, StripeApi } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/stripe.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/stripe.d')
  // @ts-ignore
  export type { VimeoPlayerApi, VimeoPlayerInput } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/vimeo-player.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/vimeo-player.d')
  // @ts-ignore
  export type { XPixelApi, XPixelInput } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/x-pixel.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/x-pixel.d')
  // @ts-ignore
  export type { YouTubePlayerApi, YouTubePlayerInput } from '../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/youtube-player.d'
  import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/youtube-player.d')
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly ClarityOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/clarity')['ClarityOptions']>
    readonly CloudflareWebAnalyticsOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/cloudflare-web-analytics')['CloudflareWebAnalyticsOptions']>
    readonly CrispOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/crisp')['CrispOptions']>
    readonly FathomAnalyticsOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/fathom-analytics')['FathomAnalyticsOptions']>
    readonly GoogleAdsenseOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-adsense')['GoogleAdsenseOptions']>
    readonly GoogleAnalyticsOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-analytics')['GoogleAnalyticsOptions']>
    readonly GoogleMapsOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-maps')['GoogleMapsOptions']>
    readonly GoogleTagManagerOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-tag-manager')['GoogleTagManagerOptions']>
    readonly HotjarOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/hotjar')['HotjarOptions']>
    readonly IntercomOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/intercom')['IntercomOptions']>
    readonly MatomoAnalyticsOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/matomo-analytics')['MatomoAnalyticsOptions']>
    readonly MetaPixelOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/meta-pixel')['MetaPixelOptions']>
    readonly NpmOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/npm')['NpmOptions']>
    readonly PlausibleAnalyticsOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/plausible-analytics')['PlausibleAnalyticsOptions']>
    readonly SegmentOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/segment')['SegmentOptions']>
    readonly StripeOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/stripe')['StripeOptions']>
    readonly XPixelOptions: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/x-pixel')['XPixelOptions']>
    readonly abortNavigation: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['abortNavigation']>
    readonly addRouteMiddleware: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['addRouteMiddleware']>
    readonly avatarGroupInjectionKey: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup')['avatarGroupInjectionKey']>
    readonly buttonGroupInjectionKey: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useButtonGroup')['buttonGroupInjectionKey']>
    readonly callOnce: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/once')['callOnce']>
    readonly cancelIdleCallback: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/compat/idle-callback')['cancelIdleCallback']>
    readonly clearError: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/error')['clearError']>
    readonly clearNuxtData: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/asyncData')['clearNuxtData']>
    readonly clearNuxtState: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/state')['clearNuxtState']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createError: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/error')['createError']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAppConfig: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/nuxt')['defineAppConfig']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineLocale: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale')['defineLocale']>
    readonly defineNuxtComponent: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/component')['defineNuxtComponent']>
    readonly defineNuxtLink: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/components/nuxt-link')['defineNuxtLink']>
    readonly defineNuxtPlugin: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/nuxt')['defineNuxtPlugin']>
    readonly defineNuxtRouteMiddleware: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['defineNuxtRouteMiddleware']>
    readonly definePayloadPlugin: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/nuxt')['definePayloadPlugin']>
    readonly definePayloadReducer: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/payload')['definePayloadReducer']>
    readonly definePayloadReviver: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/payload')['definePayloadReviver']>
    readonly defineShortcuts: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts')['defineShortcuts']>
    readonly effect: UnwrapRef<typeof import('vue')['effect']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly extendDevtoolsMeta: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/extendDevtoolsMeta')['extendDevtoolsMeta']>
    readonly extractShortcuts: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts')['extractShortcuts']>
    readonly formBusInjectionKey: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['formBusInjectionKey']>
    readonly formFieldInjectionKey: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['formFieldInjectionKey']>
    readonly formInputsInjectionKey: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['formInputsInjectionKey']>
    readonly formLoadingInjectionKey: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['formLoadingInjectionKey']>
    readonly formOptionsInjectionKey: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['formOptionsInjectionKey']>
    readonly getAppManifest: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/manifest')['getAppManifest']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getRouteRules: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/manifest')['getRouteRules']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hasInjectionContext: UnwrapRef<typeof import('vue')['hasInjectionContext']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly injectHead: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['injectHead']>
    readonly inputIdInjectionKey: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['inputIdInjectionKey']>
    readonly isNuxtError: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/error')['isNuxtError']>
    readonly isPrerendered: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/payload')['isPrerendered']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isVue2: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/compat/vue-demi')['isVue2']>
    readonly isVue3: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/compat/vue-demi')['isVue3']>
    readonly kbdKeysMap: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useKbd')['kbdKeysMap']>
    readonly loadPayload: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/payload')['loadPayload']>
    readonly localeContextInjectionKey: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useLocale')['localeContextInjectionKey']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly mergeModels: UnwrapRef<typeof import('vue')['mergeModels']>
    readonly modalInjectionKey: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useModal')['modalInjectionKey']>
    readonly navigateTo: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['navigateTo']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onNuxtReady: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ready')['onNuxtReady']>
    readonly onPrehydrate: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['onPrehydrate']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly prefetchComponents: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/preload')['prefetchComponents']>
    readonly preloadComponents: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/preload')['preloadComponents']>
    readonly preloadPayload: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/payload')['preloadPayload']>
    readonly preloadRouteComponents: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/preload')['preloadRouteComponents']>
    readonly prerenderRoutes: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['prerenderRoutes']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly proxyRefs: UnwrapRef<typeof import('vue')['proxyRefs']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly refreshCookie: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/cookie')['refreshCookie']>
    readonly refreshNuxtData: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/asyncData')['refreshNuxtData']>
    readonly reloadNuxtApp: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/chunk')['reloadNuxtApp']>
    readonly requestIdleCallback: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/compat/idle-callback')['requestIdleCallback']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setPageLayout: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['setPageLayout']>
    readonly setResponseStatus: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['setResponseStatus']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly showError: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/error')['showError']>
    readonly slideoverInjectionKey: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useSlideover')['slideoverInjectionKey']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly tryUseNuxtApp: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/nuxt')['tryUseNuxtApp']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly updateAppConfig: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/config')['updateAppConfig']>
    readonly useAppConfig: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/config')['useAppConfig']>
    readonly useAsyncData: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/asyncData')['useAsyncData']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAvatarGroup: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup')['useAvatarGroup']>
    readonly useButtonGroup: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useButtonGroup')['useButtonGroup']>
    readonly useColorMode: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/composables')['useColorMode']>
    readonly useComponentIcons: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons')['useComponentIcons']>
    readonly useCookie: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/cookie')['useCookie']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useError: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/error')['useError']>
    readonly useFetch: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/fetch')['useFetch']>
    readonly useFormField: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useFormField')['useFormField']>
    readonly useHead: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['useHead']>
    readonly useHeadSafe: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['useHeadSafe']>
    readonly useHydration: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/hydrate')['useHydration']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useImage: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+image@1.9.0/node_modules/@nuxt/image/dist/runtime/composables')['useImage']>
    readonly useKbd: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useKbd')['useKbd']>
    readonly useLazyAsyncData: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/asyncData')['useLazyAsyncData']>
    readonly useLazyFetch: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/fetch')['useLazyFetch']>
    readonly useLoadingIndicator: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/loading-indicator')['useLoadingIndicator']>
    readonly useLocale: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useLocale')['useLocale']>
    readonly useModal: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useModal')['useModal']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNuxtApp: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/nuxt')['useNuxtApp']>
    readonly useNuxtData: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/asyncData')['useNuxtData']>
    readonly usePreviewMode: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/preview')['usePreviewMode']>
    readonly useRequestEvent: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['useRequestEvent']>
    readonly useRequestFetch: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['useRequestFetch']>
    readonly useRequestHeader: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['useRequestHeader']>
    readonly useRequestHeaders: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['useRequestHeaders']>
    readonly useRequestURL: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/url')['useRequestURL']>
    readonly useResponseHeader: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/ssr')['useResponseHeader']>
    readonly useRoute: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['useRoute']>
    readonly useRouteAnnouncer: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/route-announcer')['useRouteAnnouncer']>
    readonly useRouter: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/router')['useRouter']>
    readonly useRuntimeConfig: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/nuxt')['useRuntimeConfig']>
    readonly useRuntimeHook: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/runtime-hook')['useRuntimeHook']>
    readonly useScript: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/composables/useScript')['useScript']>
    readonly useScriptClarity: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/clarity')['useScriptClarity']>
    readonly useScriptCloudflareWebAnalytics: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/cloudflare-web-analytics')['useScriptCloudflareWebAnalytics']>
    readonly useScriptCrisp: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/crisp')['useScriptCrisp']>
    readonly useScriptEventPage: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/composables/useScriptEventPage')['useScriptEventPage']>
    readonly useScriptFathomAnalytics: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/fathom-analytics')['useScriptFathomAnalytics']>
    readonly useScriptGoogleAdsense: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-adsense')['useScriptGoogleAdsense']>
    readonly useScriptGoogleAnalytics: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-analytics')['useScriptGoogleAnalytics']>
    readonly useScriptGoogleMaps: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-maps')['useScriptGoogleMaps']>
    readonly useScriptGoogleTagManager: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/google-tag-manager')['useScriptGoogleTagManager']>
    readonly useScriptHotjar: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/hotjar')['useScriptHotjar']>
    readonly useScriptIntercom: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/intercom')['useScriptIntercom']>
    readonly useScriptLemonSqueezy: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/lemon-squeezy')['useScriptLemonSqueezy']>
    readonly useScriptMatomoAnalytics: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/matomo-analytics')['useScriptMatomoAnalytics']>
    readonly useScriptMetaPixel: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/meta-pixel')['useScriptMetaPixel']>
    readonly useScriptNpm: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/npm')['useScriptNpm']>
    readonly useScriptPlausibleAnalytics: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/plausible-analytics')['useScriptPlausibleAnalytics']>
    readonly useScriptSegment: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/segment')['useScriptSegment']>
    readonly useScriptStripe: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/stripe')['useScriptStripe']>
    readonly useScriptTriggerConsent: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/composables/useScriptTriggerConsent')['useScriptTriggerConsent']>
    readonly useScriptTriggerElement: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/composables/useScriptTriggerElement')['useScriptTriggerElement']>
    readonly useScriptVimeoPlayer: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/vimeo-player')['useScriptVimeoPlayer']>
    readonly useScriptXPixel: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/x-pixel')['useScriptXPixel']>
    readonly useScriptYouTubePlayer: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.7.0_@vue+compiler-core@3.5.13_nuxt@3.15.4_postcss@8.5.2__t335bdfrtud4ayljlw7vljqa6e/node_modules/@nuxt/scripts/dist/runtime/registry/youtube-player')['useScriptYouTubePlayer']>
    readonly useSeoMeta: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['useSeoMeta']>
    readonly useServerHead: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['useServerHead']>
    readonly useServerHeadSafe: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['useServerHeadSafe']>
    readonly useServerSeoMeta: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@unhead+vue@1.11.9_vue@3.5.13/node_modules/@unhead/vue')['useServerSeoMeta']>
    readonly useShadowRoot: UnwrapRef<typeof import('vue')['useShadowRoot']>
    readonly useSlideover: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useSlideover')['useSlideover']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useState: UnwrapRef<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_drizzle-orm@0.36.4_eslint@9.20.1_typescript@5.7.3_vite@6.1.0/node_modules/nuxt/dist/app/composables/state')['useState']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useToast: UnwrapRef<typeof import('../../../../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.10_embla-carousel@8.5.2_radix-vue@1.9.14_typescript@5.7.3_vite@6.1.0_vue@3.5.13/node_modules/@nuxt/ui/dist/runtime/composables/useToast')['useToast']>
    readonly useTransitionState: UnwrapRef<typeof import('vue')['useTransitionState']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly withCtx: UnwrapRef<typeof import('vue')['withCtx']>
    readonly withDirectives: UnwrapRef<typeof import('vue')['withDirectives']>
    readonly withKeys: UnwrapRef<typeof import('vue')['withKeys']>
    readonly withMemo: UnwrapRef<typeof import('vue')['withMemo']>
    readonly withModifiers: UnwrapRef<typeof import('vue')['withModifiers']>
    readonly withScopeId: UnwrapRef<typeof import('vue')['withScopeId']>
  }
}