name: dev_nuxthub_preview

on:
  pull_request:
    paths:
      - packages/**
      - apps/dev/**
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  nuxthub_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 22.16.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Infisical CLI
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical

      - name: Deploy to NuxtHub
        run: |
          cd apps/dev
          infisical run --domain=https://secrets.serp.co --token=${{ secrets.INFISICAL_ACCESS_TOKEN_SERP_MONOREPO_FORK }} --projectId=${{ secrets.INFISICAL_PROJECT_ID_DEV }} -- npx nuxthub deploy

      - name: Comment PR with preview URL
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **NuxtHub Preview deployed!**\n\n📱 Preview URL will be available in the deployment logs\n\n_Deployed from ${context.sha.substring(0, 7)}_`
            });